version: "3.8"
services:
  karate-test:
    image: karate-tests
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes: 
      - ./target:/usr/src/app/target
      - ~/.m2:/root/.m2
    command: mvn test